Repository checkmarx-ltd/TeamCity-Plugin, pull requests merged in 2022-03, with the labels that each got.

#24 chore: adding logs and increasing plugin version
  build/pom.xml
  cxplugin-agent/pom.xml
  cxplugin-agent/src/main/java/com/checkmarx/teamcity/agent/CxBuildProcess.java
  cxplugin-common/pom.xml
  cxplugin-server/pom.xml
  pom.xml
Labels: size/S

#23 feature: custom field implemented
  cxplugin-agent/src/main/java/com/checkmarx/teamcity/agent/CxBuildProcess.java
  cxplugin-agent/src/main/java/com/checkmarx/teamcity/agent/CxConfigHelper.java
  cxplugin-common/src/main/java/com/checkmarx/teamcity/common/CxConstants.java
  cxplugin-common/src/main/java/com/checkmarx/teamcity/common/CxParam.java
  cxplugin-server/src/main/java/com/checkmarx/teamcity/server/CxAdminPageController.java
  cxplugin-server/src/main/java/com/checkmarx/teamcity/server/CxOptions.java
  cxplugin-server/src/main/java/com/checkmarx/teamcity/server/CxRunTypePropertiesProcessor.java
  cxplugin-server/src/main/resources/buildServerResources/editRunParams.jsp
Labels: size/M

#25 Sca resolver feature
  cxplugin-agent/src/main/java/com/checkmarx/teamcity/agent/CxConfigHelper.java
  cxplugin-common/src/main/java/com/checkmarx/teamcity/common/CxConstants.java
  cxplugin-common/src/main/java/com/checkmarx/teamcity/common/CxParam.java
  cxplugin-server/src/main/java/com/checkmarx/teamcity/server/CxOptions.java
  cxplugin-server/src/main/java/com/checkmarx/teamcity/server/CxRunTypePropertiesProcessor.java
  cxplugin-server/src/main/resources/buildServerResources/editRunParams.jsp
Labels: size/L

#26 fix: removing id property for checkbox and replacing with implementat…
  cxplugin-server/src/main/resources/buildServerResources/editRunParams.jsp
Labels: size/XS

#27 Sca teampath integration
  cxplugin-agent/src/main/java/com/checkmarx/teamcity/agent/CommonClientFactory.java
  cxplugin-agent/src/main/java/com/checkmarx/teamcity/agent/CxBuildProcess.java
  cxplugin-agent/src/main/java/com/checkmarx/teamcity/agent/CxConfigHelper.java
  cxplugin-common/src/main/java/com/checkmarx/teamcity/common/CxParam.java
  cxplugin-server/src/main/java/com/checkmarx/teamcity/server/CxOptions.java
  cxplugin-server/src/main/resources/buildServerResources/editRunParams.jsp
Labels: size/M
